
service: chatbot

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  role : arn:aws:iam::843314631316:role/chatbot-dev-eu-west-2-lambdaRole
  apiGateway:
    restApiId: ajexrc4gb4
    restApiRootResourceId: qkfc6i9nvg
  # iamRoleStatements:
  #    - Effect: 'Allow'
  #      Action:
  #        - lex:readonly
  #        - lex:runbotsonly
  #      Resource: "*"

functions:
  lex_setBudget:
    handler: chatbot/setBudget.lex_setBudget
    events:
      - http:
          path: /chatbot/setBudget
          method: post
          authorizer:
            name: AuthorizationChatbot
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
plugins:
  - serverless-import-apigateway
custom:
  importApiGateway:
    name: ${self:provider.stage}-user-home