service: user-home
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  environment:
    RECEIPTS_TABLE: receipts
    BUDGETS_TABLE: budgets
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
        - "arn:aws:s3:::user-asset-bucket/*"

custom:
  assets:
    targets:
      - bucket: user-asset-bucket
        files:
          defaultContentType: image/jpeg
        acl: bucket-owner-full-control

functions:
  user:
    handler: user.home
    events:
      - http:
          path: /user
          method: get
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  user_update:
    handler: user_update.update
    events:
      - http:
          path: /user/pp-upload
          method: put
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  user_delete:
    handler: user_delete.delete
    events:
    - http:
        path: /user/delete
        method: post
        authorizer:
          name: Authorization
          arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  expenses_get:
    handler: expenses.get
    events:
      - http:
          path: /user/receipts
          method: get
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  expenses_post:
    handler: expenses.post
    events:
      - http:
          path: /user/receipts
          method: post
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
plugins:
  - serverless-import-apigateway
  - serverless-s3-deploy

resources:
 Resources:
   receipts:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: receipts
       AttributeDefinitions:
         - AttributeName: userId
           AttributeType: S
         - AttributeName: receiptId
           AttributeType: S
       KeySchema:
         - AttributeName: userId
           KeyType: HASH
         - AttributeName: receiptId
           KeyType: RANGE
       BillingMode: PAY_PER_REQUEST
