# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: user-home
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  environment:
    RECEIPTS_TABLE: receipts
#  apiGateway:
#    restApiId: ajexrc4gb4
#    restApiRootRessourceId: qkfc6i9nvg
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
        - "arn:aws:s3:::userbucketupload/*"

functions:
  user:
    handler: user.home
    events:
      - http:
          path: /user
          method: get
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  user_pp_put:
    handler: user_picture.put
    events:
      - http:
          path: /user/pp-upload
          method: put
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
      - s3:
          bucket: userbucketupload
          event: s3:ObjectCreated:*
  user_pp_get:
    handler: user_picture.get
    events:
      - http:
          path: /user/pp-upload
          method: get
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  user_pp_delete:
    handler: user_picture.delete
    events:
    - http:
        path: /user/pp-upload
        method: delete
        authorizer:
          name: Authorization
          arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
#plugins:
#  - serverless-import-apigateway
#custom:
#  importApiGateway:
#    name: ${self:provider.stage}-user-home
