service: user-home
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  environment:
    RECEIPTS_TABLE: receipts
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::*/*"
    - Effect: 'Allow'
      Action:
        - "s3:*"
        - 's3:ListBucket'
      Resource: "arn:aws:s3:::*/*"
    - Effect: 'Allow'
      Action:
        - "cognito-idp:AdminUpdateUserAttributes"
      Resource: "arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M"
  apiGateway:
    binaryMediaTypes:
          - '*/*'

functions:
  user:
    handler: user.home
    events:
      - http:
          path: /user
          method: get
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  user_pp_get:
    handler: user_picture.get
    events:
      - http:
          path: /user/pp-upload
          method: get
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
      - s3:
          bucket: users-profile-picture
          event: "s3:ObjectCreated:*"
  user_pp_post:
    handler: user_picture.post
    events:
      - http:
          path: /user/pp-upload
          method: post
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  user_pp_delete:
    handler: user_picture.delete
    events:
    - http:
        path: /user/pp-upload
        method: delete
        authorizer:
          name: Authorization
          arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M