service: budgets

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  role : arn:aws:iam::843314631316:role/chatbot-dev-eu-west-2-lambdaRole
  apiGateway:
    restApiId: ajexrc4gb4
    restApiRootResourceId: qkfc6i9nvg
  environment:
    BUDGETS_TABLE: budgets

functions:
  budgets_get:
    handler: budgets/budgets.budgetsFunction.get
    events:
      - http:
          path: /user/budgets
          method: get
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
  budgets_post:
    handler: budgets/budgets.budgetsFunction.post
    events:
      - http:
          path: /user/budgets
          method: post
          authorizer:
            name: Authorization
            arn: arn:aws:cognito-idp:eu-west-2:843314631316:userpool/eu-west-2_kT5EeqP0M
plugins:
  - serverless-import-apigateway
custom:
  importApiGateway:
    name: ${self:provider.stage}-user-home
resources:
 Resources:
   budgets:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: budgets
       AttributeDefinitions:
         - AttributeName: userId
           AttributeType: S
         - AttributeName: budgetsId
           AttributeType: S
       KeySchema:
         - AttributeName: userId
           KeyType: HASH
         - AttributeName: budgetsId
           KeyType: RANGE
       BillingMode: PAY_PER_REQUEST
