service: my-pdf

provider:
  name: aws
  runtime: nodejs12.x
  logRetentionInDays: 1
  region: eu-west-2

  environment:
    FEED_BUCKET_NAME: !Ref ScraperFeedBucket
    HTTP_CACHE_BUCKET_NAME: !Ref HttpCacheBucket
    CONTAINER_NAME: "pdf_generator_container"
    ECS_CLUSTER: !GetAtt FargateECSCluster.Arn
    ECS_TASK_ARN: !Ref FargateECSTaskDefinition
    ECS_SUBNET: !Ref FargateSubnet
    ECS_SEC_GROUP: !Ref FargateSG

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: !Sub
        - "arn:aws:s3:::#{BucketName}/*"
        - BucketName: !Ref ScraperFeedBucket
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:ListBucket"
      Resource:
        - !Sub
          - "arn:aws:s3:::#{BucketName}/*"
          - BucketName: !Ref HttpCacheBucket
        - !Sub
          - "arn:aws:s3:::#{BucketName}"
          - BucketName: !Ref HttpCacheBucket

    - Effect: Allow
      Action:
        - ecs:RunTask
      Resource:
        - !Ref FargateECSTaskDefinition
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource:
        - !GetAtt FargateExecutionRole.Arn
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource:
        - !GetAtt FargateTaskRole.Arn

functions:
  launchGenerationPDF:
    handler: handler.launch

resources:
  - AWSTemplateFormatVersion: "2010-09-09"
    Transform: "AWS::Serverless-2016-10-31"
  - ${file(./s3-template.yml)}
  - ${file(./fargate-template.yml)}

plugins:
  - serverless-cloudformation-sub-variables
